### ISSUE TITLE
dyncould-instructor-student

### ISSUE THREAD

**Issue by desaiyang** [desaiyang/instructor-student#1]
![image](https://user-images.githubusercontent.com/60084078/93982556-fb3d9a80-fd9e-11ea-9d6e-c59e201f3f95.png)

**Comment by desaiyang** [comment]
![Uploading image.png…]()

**Comment by desaiyang** [comment]
![Uploading image.png…]()

**Comment by desaiyang** [comment]
not urgent .. 1 week..

![image](https://user-images.githubusercontent.com/60084078/94283733-03e4cb00-ff6f-11ea-9012-6a014686ff83.png)

**Comment by desaiyang** [comment]
![image](https://user-images.githubusercontent.com/60084078/94584874-dd8b9c00-029c-11eb-917f-817044cb0eb3.png)

**Comment by desaiyang** [comment]
keep passwords.
instructor1 - student1, student2, student3, student4, student5

branch arec code and call it 5.0 or webschool 5.0

add a link into the first page of dyncould.com for webschool.

webschool-1

click on it show 2 different login one for instructor and one for the student
when instructor logic rename arec in to instructor1 and show main menus class prep, class todos, class files, and in class prep rename surfacing in to class prep work .. and in class todos instead of flooring change to class todos tracker .. and instead of dynspace change to class files .. that will do for now. ok. 

and for the trng login on the other side change to students1,2,3 ... login.
make some good image for login screen.

and then what give the logins to the web instructor and send the password after verify.

take 3 weeks to code for this new schema - webschool.

remember finally all you need is a link on the main page and a 1:5 input panels.

**Comment by desaiyang** [comment]
![image](https://user-images.githubusercontent.com/60084078/94838406-26755900-0433-11eb-9922-2dfa1f31d049.png)

**Comment by desaiyang** [comment]
![image](https://user-images.githubusercontent.com/60084078/94849190-a951e000-0442-11eb-98b7-04d5af856356.png)

**Comment by desaiyang** [comment]
![image](https://user-images.githubusercontent.com/60084078/95326613-7c794f00-08c0-11eb-8ee3-eef9c88c8bee.png)

**Comment by desaiyang** [comment]
![image](https://user-images.githubusercontent.com/60084078/95327218-51dbc600-08c1-11eb-8f28-538b4153fa93.png)

**Comment by desaiyang** [comment]
![image](https://user-images.githubusercontent.com/60084078/95332363-f01f5a00-08c8-11eb-8acc-533aa8c4586a.png)

**Comment by desaiyang** [comment]
my new design for building web school online. the idea is i got aREC and trng. 2 different website. now aREC can be called as a teacher and trng can be called as training. let me start from the trng website. web class notes, web class todos, and web class files can be stored and can be approved from the instructor online. i am going to repeat this same set for a subject and continue my programming on the side. for subject 1 there will be a schema with same set of table as in trng123, etc. the code for subject 1 should display subject 1 in web class notes, todos, and dynspace. 

![image](https://user-images.githubusercontent.com/60084078/95340796-3b3e6a80-08d3-11eb-9d2d-7ad20b9e8593.png)

**Comment by arec2053** [comment]
![image](https://user-images.githubusercontent.com/70337213/95354582-3503ba80-08e2-11eb-89d2-dab3efd52446.png)

**Comment by desaiyang** [comment]
![image](https://user-images.githubusercontent.com/60084078/95370281-28895d00-08f6-11eb-9b80-62c0f64d0fab.png)

**Comment by arec2053** [comment]
the idea is good. for the first release of webschool1 you dont need a integrator with auto process. i would stop first. use arec183 as instructor and use trng154, trng155, trng156, trng157 as those 4 students. first create accounts for these 5.

when **arec183@webschool1.com** logs in show only **trng154, trng155, trng156, trng157** when the **trngs submit button** is clicked in the aREC website in surface, floor or dynSPACE web pages.

the above method will give you are webschool1 for the above team which you can show it any one for demo or even sell it or ask them to try for free. its is up to you. 

in the existing aREC as well as trng web code or db code (you can use dyncould_approved to group the above web school 1) and a cool text for the logged in user that they are in webschool1/ this is your team / these are your subjects / these are the topics for each subject / this is class schedule / this is the announcement for the web school 1 / etc ...

also couple of button while are183@webschool1.com logs in - after clicking trngs - simply a submit button called 'announce' and 'message'. 

a) announce - will send to all 4 students defined as above.
b) message - will show which one to send message

other things like, should the web instructor have access to all the records of the trngs - i don't know. in my training web dev i am not having access to students records at all. so discuss with whomever is the buyer of this website. ok.

the above itself will take 3 weeks. so relax and code slow.

**Comment by desaiyang** [comment]
designing the web instructor view in aREC for trngs will be interesting. what should i be displaying. very simple start from showing the announcements to the web school 1 and the list of trngs.  

when trng187 is selected show the numbered messages to the web instructor..

also show the files posted by web instructor to the web school 1 in the school locker. 

![image](https://user-images.githubusercontent.com/60084078/95747728-87642300-0cb6-11eb-9d7d-c6e6df1ae17c.png)

**Comment by desaiyang** [comment]
to complete the web instructor steps announce is the table in arec58 table. this needs to be populated to all arec accounts so that the web instructor (teacher) can announce to the trngs (students). so it is for the instructor. keep the color black.

feature needed for - 11/1 drop.

**Comment by desaiyang** [comment]
**gd 10/19 - status on new functionality for web school - announce, message + bug fixes.**

1) **announce**  - with this feature the instructor can send messages to the grouped trng_ids for a specific webshool1 and the students get the announcements in the first page after login.
2) **message** - with this feature the instructor can send any time message to a specific student
3) **q&a** - questions from students are sent immediately to the instructor and the instructor can answer the questions. the q&a tab will have all questions from students and answers from the instructor.
4) **todos** - the students can assign todos with custom topics describing problems on subjects/class of their own to the instructor and the instructor responses are sent back to students immediately to solve problems. the instructor tab in the application shows all the todos to the instructor and the instructor responses with solutions for the problem.
3) **files approval process** - after uploading, reviewing the files, the students can set the file status to pending approval. as soon as the instructor reviews the status can be set to approved.
4) coded, tested and ready for 11/1 drop.

**Comment by desaiyang** [comment]
![image](https://user-images.githubusercontent.com/60084078/97038356-4efef780-1588-11eb-9fa6-99d856838851.png)

**Comment by arec2053** [comment]
how to create a better learning experience, home talks and business handlings ...

![image](https://user-images.githubusercontent.com/70337213/98668026-46266800-2375-11eb-9c3a-72babca1bbda.png)

**Comment by desaiyang** [comment]
closing .. for review

gd
12/28
